### ISSUE TITLE
CSS for Likert Questionnaires

### ISSUE THREAD

**Issue by steffejr** [jspsych/experiment-demos#17]
Hello all,
I am implementing some questionnaires. I cannot figure out how to work with the style of it though. Can anyone help please?

https://github.com/NCMlab/experiment-demos/blob/main/LikertQuestionnaires/test.html

Jason

**Comment by pjkohler** [comment]
what is it you are specifically trying to do?

**Comment by pjkohler** [comment]
Could you just use a css file to style the document? Looks pretty cool so far.

**Comment by steffejr** [comment]
I would like to be able to change the font size/style of the instructions and questions. To make it pretty. I just can't seem to figure out what to change/add to have any effect on the questions.

**Comment by pjkohler** [comment]
well, first of all add the jspsych.css file to your header.

**Comment by steffejr** [comment]
Duh, I figured it out. I had a comment at the top of my HTML file that was messing everything up.

**Comment by pjkohler** [comment]
very cool!
